version: '3.4'

services:
  htwai21swegrpb02:
    image: htwai21swegrpb02
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ${HOST_VOLUME_PATH}:/app/data
