name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        
    - name: Push Container
      run: 
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
