name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag ghcr.io/techchrobe/htwai21swegrpb02:latest
        
    - name: Push Container
      run: |
        docker run ghcr.io/techchrobe/htwai21swegrpb02:latest
        docker push ghcr.io/techchrobe/htwai21swegrpb02:latest
      
