# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        apt-get update
        apt-get --yes install libmagic1
        python -m pip install --upgrade pip
        pip install flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Unittest
      run: |
        cd file-repository/Test
        python -m unittest discover tests -s .
