# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # rabbitmq-start:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v2

  #     - name: start rabbit mq
  #       run: docker run --detach --name ai21-ws21-swe-rabbitmq --publish 5672:5672 --publish 15672:15672 rabbitmq:3

  #     # - name: Start RabbitMQ
  #     #   uses: namoshek/rabbitmq-github-action@v1
  #     #   with:
  #     #     version: '3.8.9'
  #     #     ports: '1883:1883 8883:8883' # TODO other ports?
  #     #     container-name: 'ai21-ws21-swe-rabbitmq'
  #         # TODO create custom docker image for rabbit mq? 
  #         # TODO use env variables or something else to reduce redunantly declaring things like container-name etc
  #    # - run: test

  build:
    # needs: rabbitmq-start
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: edit docker dns options
      run: echo 'DOCKER_OPTS="--dns 8.8.8.8 --dns 10.252.252.252"' >> /etc/defaul/docker
    - name: start rabbit mq
      run: sudo docker run --detach --name ai21-ws21-swe-rabbitmq --publish 5672:5672 --publish 15672:15672 rabbitmq:3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Unittest
      run: |
        cd Test
        python -m unittest discover tests -s .
